CREATE FUNCTION STC_GET_RATE_PER_MILE( iDLID INT )
  RETURNS DOUBLE
  LANGUAGE SQL
  READS SQL DATA
  NOT DETERMINISTIC
BEGIN
  DECLARE vCHARGES DOUBLE DEFAULT 0;
  DECLARE vDISTANCE DOUBLE DEFAULT 0;
  DECLARE vRATE DOUBLE DEFAULT 0;

  SELECT COALESCE( D.RATE, 0)
  INTO vRATE
  FROM TLDTL D
  WHERE D.ORDER_ID = iDLID
  FETCH FIRST 1 ROW ONLY;

  SELECT COALESCE( T.CHARGES, 0), COALESCE( T.DISTANCE, 0)
  INTO vCHARGES, vDISTANCE
  FROM TLORDER T
  WHERE T.DETAIL_LINE_ID = iDLID
  FETCH FIRST 1 ROW ONLY;

  IF vRATE = vCHARGES THEN
    RETURN ROUND(FLOAT(vCHARGES)/FLOAT(vDISTANCE),2);
  ELSE
    RETURN ROUND(vRATE,2);
  END IF;
END