--<ScriptOptions statementTerminator="@"/>

CREATE OR REPLACE PROCEDURE STC_UPD_DATES( IN iDLID INTEGER,
	IN iPICK_UP_BY TIMESTAMP,
	IN iPICK_UP_BY_END TIMESTAMP,
	IN iDELIVER_BY TIMESTAMP,
	IN iDELIVER_BY_END TIMESTAMP )
	LANGUAGE SQL 
BEGIN	
	UPDATE TLORDER
		SET PICK_UP_BY = iPICK_UP_BY,
			PICK_UP_BY_END = iPICK_UP_BY_END
		WHERE MASTER_ORDER = iDLID
		AND EXTRA_STOPS = 'Child';
END@

CREATE OR REPLACE TRIGGER STC_TLORDER_UPD_DATES
	AFTER UPDATE ON TLORDER
	REFERENCING NEW AS N OLD AS O
	FOR EACH ROW
	MODE DB2SQL
BEGIN ATOMIC
	IF O.BILL_NUMBER = 'NA'
	--	AND N.BILL_NUMBER != 'NA'
		AND N.EXTRA_STOPS = 'True'
		AND N.NO_STOPS > 0 THEN
		
		CALL STC_UPD_DATES( N.DETAIL_LINE_ID,
			N.PICK_UP_BY, N.PICK_UP_BY_END, N.DELIVER_BY, N.DELIVER_BY_END );
	END IF;
END@


--<ScriptOptions statementTerminator="@"/>

CREATE OR REPLACE TRIGGER STC_TLORDER_UPD_SITE9
	AFTER UPDATE ON TLORDER
	REFERENCING NEW AS N OLD AS O
	FOR EACH ROW
	MODE DB2SQL
BEGIN ATOMIC
	IF N.SITE_ID = 'SITE9'
		AND N.EXTRA_STOPS = 'True'
		AND N.NO_STOPS > 0 THEN
		
		CALL STC_UPD_DATES( N.DETAIL_LINE_ID,
			N.PICK_UP_BY, N.PICK_UP_BY_END, N.DELIVER_BY, N.DELIVER_BY_END );
	END IF;
END@
