--<ScriptOptions statementTerminator="@"/>

--DECLARE vEXEC VARCHAR(256) DEFAULT 'DROP PROCEDURE CUSTOM_GEN_ID';


CREATE PROCEDURE CUSTOM_GEN_ID(
	IN iGEN_NAME VARCHAR(128)
)
	LANGUAGE SQL
	DYNAMIC RESULT SETS 1
BEGIN
	DECLARE oNEXT_ID INT DEFAULT 0;
	DECLARE c1 CURSOR WITH RETURN FOR
       SELECT 
           oNEXT_ID AS NEXTID
       FROM
          SYSIBM.SYSDUMMY1;
  
	CALL GEN_ID(iGEN_NAME, oNEXT_ID); 

	OPEN c1;
END@

--DECLARE vEXEC VARCHAR(256) DEFAULT 'DROP PROCEDURE CUSTOM_GET_CLIENT_ID';


CREATE PROCEDURE CUSTOM_GET_CLIENT_ID(
  IN  iNAME VARCHAR(40),
  IN  iPROVINCE VARCHAR(4),
  IN  iCITY VARCHAR(30)
)
	LANGUAGE SQL
	DYNAMIC RESULT SETS 1
BEGIN
	DECLARE oCLIENT_ID VARCHAR(10) DEFAULT '';
	DECLARE oRESULT INTEGER DEFAULT 0;

	DECLARE c1 CURSOR WITH RETURN FOR
       SELECT 
           oCLIENT_ID AS CLIENT_ID
       FROM
          SYSIBM.SYSDUMMY1;
  
	CALL PROFILE_GET_CLIENT_ID(iNAME, iPROVINCE, iCITY, oCLIENT_ID, oRESULT);
	
	OPEN c1;
END@

CREATE PROCEDURE CUSTOM_GET_MILEAGE_FROMTO(
	IN iFROM_ZONE	VARCHAR(255),
	IN  iTO_ZONE	VARCHAR(255)
)
	LANGUAGE SQL
	DYNAMIC RESULT SETS 1
BEGIN
	DECLARE oDISTANCE		DOUBLE;
    DECLARE oFLATPAY		DOUBLE;
    DECLARE oTOLLS			DOUBLE;
	DECLARE oSTATUSCODE		INTEGER;
    DECLARE oSTATUSMSG		VARCHAR(255);      

	DECLARE c1 CURSOR WITH RETURN FOR
       SELECT 
           oDISTANCE AS DISTANCE
       FROM
          SYSIBM.SYSDUMMY1;
  
	CALL GET_MILEAGE_FROMTO('DEFAULT', iFROM_ZONE, iTO_ZONE, oDISTANCE, oFLATPAY,
								oTOLLS, oSTATUSCODE, oSTATUSMSG); 

	OPEN c1;
END@



CREATE TABLE ST_CMS_USERS (
	USERID VARCHAR(128) NOT NULL,
	PASSWORD VARCHAR(32) NOT NULL,
	FULLNAME VARCHAR(40) NOT NULL,
	EMAIL VARCHAR(64) NOT NULL,
	ADMIN VARCHAR(8) CHECK(ADMIN IN ('True', 'False')),
	GROUPS VARCHAR(64),
	UNIQUE(USERID)
)@

INSERT INTO ST_CMS_USERS (USERID, PASSWORD, FULLNAME, EMAIL, GROUPS)
VALUES('ADMINISTRATOR','youdaman','Admin Account','duncan@strongtco.com',
'sysadmin,admin,crm,bms,rm,pricing,hr')@